---
title: "Julian's Sandbox"
output: html_notebook
---

# Environment Setup
```{r}
# clear junk
rm(list = ls())
```

```{r include = FALSE}
# make sure your working directory is set to datafest2022

library(readr)
library(tidyverse)
library(data.table)
```

```{r}
setwd("C:/Users/julia/Documents/GitHub/datafest2022/data")

s5 <- read_csv("./S5_scores_cleaned.csv")
```

```{r}
logs <- fread("C:\\Users\\julia\\Downloads\\logs.csv")
```

```{r}
temp <- data.frame(s5)
temp <- temp[complete.cases(temp), ]

temp <- pivot_wider(temp, id_cols = player_id, names_from = weeks, names_prefix = "week", values_from = S5_mean)
s5_wide <- temp[complete.cases(temp), ]
```

```{r}
s5_wide
```
```{r}
# non-parametric bootstrap
# parameters for bootstrapping
bs_count <- 1000
bs_size <- 100

# output datasets
bs_results <- list()
bs_mean_results <- data.frame(matrix(nrow = bs_count, ncol = 5))

for (i in seq_len(bs_count)) {
    temp <- s5_wide[sample(seq_len(nrow(s5_wide)), bs_size, replace = TRUE), ]
    bs_results[[i]] <- temp
    bs_mean_results[i,] <- colMeans(temp)[-1]
}
```

```{r}
# cleaning bs_mean_results
names(bs_mean_results) <- c("week0_bs_mean", "week3_bs_mean", "week6_bs_mean",
                            "week12_bs_mean", "week24_bs_mean")
```



```{r}
# quantile for attribute 1
alpha <- 0.05
quantile(bs_mean_results$week0_bs_mean, c(0.025, 0.975))
```

```{r}
#
```


